@organizationId = d95b09bb-727d-46a4-9a95-3c2b60a41b3f

PUT {{host}}/organizations/{{organizationId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Organization",
  "description": "Organization description",
}