services:
  mirai-api:
    container_name: mirai-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5001:5001
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      mirai-db:
        condition: service_healthy

  mirai-db:
    container_name: mirai-db
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mirai
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d mirai"]
      interval: 5s
      timeout: 5s
      retries: 5

  mirai-idp:
    container_name: mirai-idp
    image: quay.io/keycloak/keycloak:latest
    command: start-dev --import-realm
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KEYCLOAK_LOGLEVEL=DEBUG
    volumes:
      - keycloak_data:/opt/jboss/keycloak/standalone/data
      - ./.files/mirai-realm-export.json:/opt/keycloak/data/import/realm.json
    ports:
      - 18080:8080

volumes:
  postgres_data:
  keycloak_data:
