services:
  webapp:
    container_name: mirai-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      db:
        condition: service_healthy

  keycloak:
    container_name: mirai-keycloak
    image: quay.io/keycloak/keycloak:latest
    command: start-dev
    environment:
      - KC_HEALTH_ENABLED=true
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://mirai-db:5432/mirai
      - KC_DB_USERNAME=postgres
      - KC_DB_PASSWORD=postgres
      - KC_DB_URL_PROPERTIES=ssl=false
    ports:
      - "18080:8080"
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: mirai-db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mirai
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d mirai"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
