# @name create
POST {{host}}/projects
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Organization",
  "description": "Organization description",
}

### Get based on location header
GET {{create.response.headers.Location}}