# @name create
POST {{host}}/wiki-pages
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "projectId": "c09f852d-9f08-4227-be94-4be43eea1bdc",
  "title": "My new wiki page",
  "content": "This is a new wiki page",
  "parentWikiPageId": "c09f852d-9f08-4227-be94-4be43eea1bdc",
}

### Get based on location header
GET {{create.response.headers.Location}}