// <auto-generated />
using System;
using System.Collections.Generic;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250809213150_AddUsersToTeams")]
    partial class AddUsersToTeams
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Boards.Board", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_boards");

                    b.HasIndex("TeamId")
                        .IsUnique()
                        .HasDatabaseName("ix_boards_team_id");

                    b.ToTable("boards", (string)null);
                });

            modelBuilder.Entity("Domain.Boards.BoardCard", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BoardColumnId")
                        .HasColumnType("uuid")
                        .HasColumnName("board_column_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("WorkItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("work_item_id");

                    b.HasKey("Id")
                        .HasName("pk_board_cards");

                    b.HasIndex("BoardColumnId")
                        .HasDatabaseName("ix_board_cards_board_column_id");

                    b.HasIndex("WorkItemId")
                        .IsUnique()
                        .HasDatabaseName("ix_board_cards_work_item_id");

                    b.HasIndex("BoardColumnId", "Position")
                        .IsUnique()
                        .HasDatabaseName("ix_board_cards_board_column_id_position");

                    b.ToTable("board_cards", (string)null);
                });

            modelBuilder.Entity("Domain.Boards.BoardColumn", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BoardId")
                        .HasColumnType("uuid")
                        .HasColumnName("board_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DefinitionOfDone")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("definition_of_done");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<int?>("WipLimit")
                        .HasColumnType("integer")
                        .HasColumnName("wip_limit");

                    b.HasKey("Id")
                        .HasName("pk_board_columns");

                    b.HasIndex("BoardId")
                        .HasDatabaseName("ix_board_columns_board_id");

                    b.HasIndex("BoardId", "Position")
                        .IsUnique()
                        .HasDatabaseName("ix_board_columns_board_id_position");

                    b.ToTable("board_columns", (string)null);
                });

            modelBuilder.Entity("Domain.Organizations.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_organizations");

                    b.ToTable("organizations", (string)null);
                });

            modelBuilder.Entity("Domain.Personas.Persona", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<Guid?>("ImageFileId")
                        .HasColumnType("uuid")
                        .HasColumnName("image_file_id");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_personas");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_personas_project_id");

                    b.ToTable("personas", (string)null);
                });

            modelBuilder.Entity("Domain.Projects.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_projects");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_projects_organization_id");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("Domain.Retrospectives.Retrospective", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("MaxVotesPerUser")
                        .HasColumnType("integer")
                        .HasColumnName("max_votes_per_user");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<int>("Template")
                        .HasColumnType("integer")
                        .HasColumnName("template");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_retrospectives");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("ix_retrospectives_team_id");

                    b.ToTable("retrospectives", (string)null);
                });

            modelBuilder.Entity("Domain.Retrospectives.RetrospectiveColumn", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<Guid>("RetrospectiveId")
                        .HasColumnType("uuid")
                        .HasColumnName("retrospective_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_retrospective_columns");

                    b.HasIndex("RetrospectiveId")
                        .HasDatabaseName("ix_retrospective_columns_retrospective_id");

                    b.ToTable("retrospective_columns", (string)null);
                });

            modelBuilder.Entity("Domain.Retrospectives.RetrospectiveItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<Guid>("RetrospectiveColumnId")
                        .HasColumnType("uuid")
                        .HasColumnName("retrospective_column_id");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<int>("Votes")
                        .HasColumnType("integer")
                        .HasColumnName("votes");

                    b.HasKey("Id")
                        .HasName("pk_retrospective_items");

                    b.HasIndex("AuthorId")
                        .HasDatabaseName("ix_retrospective_items_author_id");

                    b.HasIndex("RetrospectiveColumnId")
                        .HasDatabaseName("ix_retrospective_items_retrospective_column_id");

                    b.ToTable("retrospective_items", (string)null);
                });

            modelBuilder.Entity("Domain.Sprints.Sprint", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_sprints");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("ix_sprints_team_id");

                    b.ToTable("sprints", (string)null);
                });

            modelBuilder.Entity("Domain.TagImportJobs.TagImportJob", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.PrimitiveCollection<List<string>>("Errors")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("errors");

                    b.Property<int>("FailedRecords")
                        .HasColumnType("integer")
                        .HasColumnName("failed_records");

                    b.Property<byte[]>("FileContent")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("file_content");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("file_name");

                    b.Property<int>("ProcessedRecords")
                        .HasColumnType("integer")
                        .HasColumnName("processed_records");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("SuccessfulRecords")
                        .HasColumnType("integer")
                        .HasColumnName("successful_records");

                    b.Property<int>("TotalRecords")
                        .HasColumnType("integer")
                        .HasColumnName("total_records");

                    b.HasKey("Id")
                        .HasName("pk_tag_import_jobs");

                    b.ToTable("tag_import_jobs", (string)null);
                });

            modelBuilder.Entity("Domain.Tags.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("color");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_tags");

                    b.HasIndex("ProjectId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_tags_project_id_name");

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("Domain.Teams.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_teams");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_teams_project_id");

                    b.HasIndex("ProjectId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_teams_project_id_name");

                    b.ToTable("teams", (string)null);
                });

            modelBuilder.Entity("Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("first_name");

                    b.Property<string>("IdentityId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("identity_id");

                    b.Property<Guid?>("ImageFileId")
                        .HasColumnType("uuid")
                        .HasColumnName("image_file_id");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("image_url");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("IdentityId")
                        .IsUnique()
                        .HasDatabaseName("ix_users_identity_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Domain.WikiPages.WikiPage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("ParentWikiPageId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_wiki_page_id");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_wiki_pages");

                    b.HasIndex("AuthorId")
                        .HasDatabaseName("ix_wiki_pages_author_id");

                    b.HasIndex("ParentWikiPageId")
                        .HasDatabaseName("ix_wiki_pages_parent_wiki_page_id");

                    b.HasIndex("ProjectId", "ParentWikiPageId", "Position")
                        .HasDatabaseName("ix_wiki_pages_project_id_parent_wiki_page_id_position");

                    b.ToTable("wiki_pages", (string)null);
                });

            modelBuilder.Entity("Domain.WikiPages.WikiPageComment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("WikiPageId")
                        .HasColumnType("uuid")
                        .HasColumnName("wiki_page_id");

                    b.HasKey("Id")
                        .HasName("pk_wiki_page_comments");

                    b.HasIndex("AuthorId")
                        .HasDatabaseName("ix_wiki_page_comments_author_id");

                    b.HasIndex("WikiPageId")
                        .HasDatabaseName("ix_wiki_page_comments_wiki_page_id");

                    b.ToTable("wiki_page_comments", (string)null);
                });

            modelBuilder.Entity("Domain.WikiPages.WikiPageView", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("ViewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("viewed_at");

                    b.Property<Guid>("ViewerId")
                        .HasColumnType("uuid")
                        .HasColumnName("viewer_id");

                    b.Property<Guid>("WikiPageId")
                        .HasColumnType("uuid")
                        .HasColumnName("wiki_page_id");

                    b.HasKey("Id")
                        .HasName("pk_wiki_page_views");

                    b.HasIndex("ViewerId")
                        .HasDatabaseName("ix_wiki_page_views_viewer_id");

                    b.HasIndex("WikiPageId")
                        .HasDatabaseName("ix_wiki_page_views_wiki_page_id");

                    b.ToTable("wiki_page_views", (string)null);
                });

            modelBuilder.Entity("Domain.WorkItems.WorkItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AcceptanceCriteria")
                        .HasColumnType("text")
                        .HasColumnName("acceptance_criteria");

                    b.Property<Guid?>("AssignedTeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_team_id");

                    b.Property<Guid?>("AssignedUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_user_id");

                    b.Property<int>("Code")
                        .HasColumnType("integer")
                        .HasColumnName("code");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid?>("ParentWorkItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_work_item_id");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<Vector>("SearchVector")
                        .IsRequired()
                        .HasColumnType("vector")
                        .HasColumnName("search_vector");

                    b.Property<Guid?>("SprintId")
                        .HasColumnType("uuid")
                        .HasColumnName("sprint_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.ComplexProperty<Dictionary<string, object>>("Classification", "Domain.WorkItems.WorkItem.Classification#Classification", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("ValueArea")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("classification_value_area");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Planning", "Domain.WorkItems.WorkItem.Planning#Planning", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int?>("Priority")
                                .HasColumnType("integer")
                                .HasColumnName("planning_priority");

                            b1.Property<int?>("StoryPoints")
                                .HasColumnType("integer")
                                .HasColumnName("planning_story_points");
                        });

                    b.HasKey("Id")
                        .HasName("pk_work_items");

                    b.HasIndex("AssignedTeamId")
                        .HasDatabaseName("ix_work_items_assigned_team_id");

                    b.HasIndex("AssignedUserId")
                        .HasDatabaseName("ix_work_items_assigned_user_id");

                    b.HasIndex("ParentWorkItemId")
                        .HasDatabaseName("ix_work_items_parent_work_item_id");

                    b.HasIndex("SprintId")
                        .HasDatabaseName("ix_work_items_sprint_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_work_items_status");

                    b.HasIndex("Type")
                        .HasDatabaseName("ix_work_items_type");

                    b.HasIndex("ProjectId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_work_items_project_id_code");

                    b.ToTable("work_items", (string)null);
                });

            modelBuilder.Entity("Domain.WorkItems.WorkItemComment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("WorkItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("work_item_id");

                    b.HasKey("Id")
                        .HasName("pk_work_item_comments");

                    b.HasIndex("AuthorId")
                        .HasDatabaseName("ix_work_item_comments_author_id");

                    b.HasIndex("WorkItemId")
                        .HasDatabaseName("ix_work_item_comments_work_item_id");

                    b.ToTable("work_item_comments", (string)null);
                });

            modelBuilder.Entity("OrganizationUsers", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("OrganizationId", "UserId")
                        .HasName("pk_organization_users");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_organization_users_organization_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_organization_users_user_id");

                    b.ToTable("OrganizationUsers", (string)null);
                });

            modelBuilder.Entity("ProjectUsers", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("ProjectId", "UserId")
                        .HasName("pk_project_users");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_project_users_project_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_project_users_user_id");

                    b.ToTable("ProjectUsers", (string)null);
                });

            modelBuilder.Entity("TagWorkItem", b =>
                {
                    b.Property<Guid>("TagsId")
                        .HasColumnType("uuid")
                        .HasColumnName("tags_id");

                    b.Property<Guid>("WorkItemsId")
                        .HasColumnType("uuid")
                        .HasColumnName("work_items_id");

                    b.HasKey("TagsId", "WorkItemsId")
                        .HasName("pk_work_item_tags");

                    b.HasIndex("WorkItemsId")
                        .HasDatabaseName("ix_work_item_tags_work_items_id");

                    b.ToTable("work_item_tags", (string)null);
                });

            modelBuilder.Entity("TeamUsers", b =>
                {
                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("TeamId", "UserId")
                        .HasName("pk_team_users");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("ix_team_users_team_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_team_users_user_id");

                    b.ToTable("TeamUsers", (string)null);
                });

            modelBuilder.Entity("Domain.Boards.Board", b =>
                {
                    b.HasOne("Domain.Teams.Team", "Team")
                        .WithOne("Board")
                        .HasForeignKey("Domain.Boards.Board", "TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_boards_teams_team_id");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Domain.Boards.BoardCard", b =>
                {
                    b.HasOne("Domain.Boards.BoardColumn", "BoardColumn")
                        .WithMany("Cards")
                        .HasForeignKey("BoardColumnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_board_cards_board_columns_board_column_id");

                    b.HasOne("Domain.WorkItems.WorkItem", "WorkItem")
                        .WithMany()
                        .HasForeignKey("WorkItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_board_cards_work_items_work_item_id");

                    b.Navigation("BoardColumn");

                    b.Navigation("WorkItem");
                });

            modelBuilder.Entity("Domain.Boards.BoardColumn", b =>
                {
                    b.HasOne("Domain.Boards.Board", "Board")
                        .WithMany("Columns")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_board_columns_boards_board_id");

                    b.Navigation("Board");
                });

            modelBuilder.Entity("Domain.Personas.Persona", b =>
                {
                    b.HasOne("Domain.Projects.Project", "Project")
                        .WithMany("Personas")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_personas_projects_project_id");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Domain.Projects.Project", b =>
                {
                    b.HasOne("Domain.Organizations.Organization", "Organization")
                        .WithMany("Projects")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_projects_organizations_organization_id");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Domain.Retrospectives.Retrospective", b =>
                {
                    b.HasOne("Domain.Teams.Team", "Team")
                        .WithMany("Retrospectives")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_retrospectives_teams_team_id");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Domain.Retrospectives.RetrospectiveColumn", b =>
                {
                    b.HasOne("Domain.Retrospectives.Retrospective", "Retrospective")
                        .WithMany("Columns")
                        .HasForeignKey("RetrospectiveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_retrospective_columns_retrospectives_retrospective_id");

                    b.Navigation("Retrospective");
                });

            modelBuilder.Entity("Domain.Retrospectives.RetrospectiveItem", b =>
                {
                    b.HasOne("Domain.Users.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_retrospective_items_users_author_id");

                    b.HasOne("Domain.Retrospectives.RetrospectiveColumn", "RetrospectiveColumn")
                        .WithMany("Items")
                        .HasForeignKey("RetrospectiveColumnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_retrospective_items_retrospective_columns_retrospective_col");

                    b.Navigation("Author");

                    b.Navigation("RetrospectiveColumn");
                });

            modelBuilder.Entity("Domain.Sprints.Sprint", b =>
                {
                    b.HasOne("Domain.Teams.Team", "Team")
                        .WithMany("Sprints")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sprints_teams_team_id");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Domain.Tags.Tag", b =>
                {
                    b.HasOne("Domain.Projects.Project", "Project")
                        .WithMany("Tags")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_tags_projects_project_id");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Domain.Teams.Team", b =>
                {
                    b.HasOne("Domain.Projects.Project", "Project")
                        .WithMany("Teams")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_teams_projects_project_id");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Domain.WikiPages.WikiPage", b =>
                {
                    b.HasOne("Domain.Users.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_wiki_pages_users_author_id");

                    b.HasOne("Domain.WikiPages.WikiPage", "ParentWikiPage")
                        .WithMany("SubWikiPages")
                        .HasForeignKey("ParentWikiPageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_wiki_pages_wiki_pages_parent_wiki_page_id");

                    b.HasOne("Domain.Projects.Project", "Project")
                        .WithMany("WikiPages")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_wiki_pages_projects_project_id");

                    b.Navigation("Author");

                    b.Navigation("ParentWikiPage");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Domain.WikiPages.WikiPageComment", b =>
                {
                    b.HasOne("Domain.Users.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_wiki_page_comments_users_author_id");

                    b.HasOne("Domain.WikiPages.WikiPage", "WikiPage")
                        .WithMany("Comments")
                        .HasForeignKey("WikiPageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_wiki_page_comments_wiki_pages_wiki_page_id");

                    b.Navigation("Author");

                    b.Navigation("WikiPage");
                });

            modelBuilder.Entity("Domain.WikiPages.WikiPageView", b =>
                {
                    b.HasOne("Domain.Users.User", "Viewer")
                        .WithMany()
                        .HasForeignKey("ViewerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_wiki_page_views_users_viewer_id");

                    b.HasOne("Domain.WikiPages.WikiPage", "WikiPage")
                        .WithMany("Views")
                        .HasForeignKey("WikiPageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_wiki_page_views_wiki_pages_wiki_page_id");

                    b.Navigation("Viewer");

                    b.Navigation("WikiPage");
                });

            modelBuilder.Entity("Domain.WorkItems.WorkItem", b =>
                {
                    b.HasOne("Domain.Teams.Team", "AssignedTeam")
                        .WithMany("WorkItems")
                        .HasForeignKey("AssignedTeamId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_work_items_teams_assigned_team_id");

                    b.HasOne("Domain.Users.User", "AssignedUser")
                        .WithMany("WorkItems")
                        .HasForeignKey("AssignedUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_work_items_users_assigned_user_id");

                    b.HasOne("Domain.WorkItems.WorkItem", "ParentWorkItem")
                        .WithMany("ChildWorkItems")
                        .HasForeignKey("ParentWorkItemId")
                        .HasConstraintName("fk_work_items_work_items_parent_work_item_id");

                    b.HasOne("Domain.Projects.Project", "Project")
                        .WithMany("WorkItems")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_work_items_projects_project_id");

                    b.HasOne("Domain.Sprints.Sprint", "Sprint")
                        .WithMany("WorkItems")
                        .HasForeignKey("SprintId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_work_items_sprints_sprint_id");

                    b.Navigation("AssignedTeam");

                    b.Navigation("AssignedUser");

                    b.Navigation("ParentWorkItem");

                    b.Navigation("Project");

                    b.Navigation("Sprint");
                });

            modelBuilder.Entity("Domain.WorkItems.WorkItemComment", b =>
                {
                    b.HasOne("Domain.Users.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_work_item_comments_users_author_id");

                    b.HasOne("Domain.WorkItems.WorkItem", "WorkItem")
                        .WithMany("Comments")
                        .HasForeignKey("WorkItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_work_item_comments_work_items_work_item_id");

                    b.Navigation("Author");

                    b.Navigation("WorkItem");
                });

            modelBuilder.Entity("OrganizationUsers", b =>
                {
                    b.HasOne("Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_organization_users_organizations_organization_id");

                    b.HasOne("Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_organization_users_users_user_id");
                });

            modelBuilder.Entity("ProjectUsers", b =>
                {
                    b.HasOne("Domain.Projects.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_users_projects_project_id");

                    b.HasOne("Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_users_users_user_id");
                });

            modelBuilder.Entity("TagWorkItem", b =>
                {
                    b.HasOne("Domain.Tags.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_work_item_tags_tags_tags_id");

                    b.HasOne("Domain.WorkItems.WorkItem", null)
                        .WithMany()
                        .HasForeignKey("WorkItemsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_work_item_tags_work_items_work_items_id");
                });

            modelBuilder.Entity("TeamUsers", b =>
                {
                    b.HasOne("Domain.Teams.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_team_users_teams_team_id");

                    b.HasOne("Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_team_users_users_user_id");
                });

            modelBuilder.Entity("Domain.Boards.Board", b =>
                {
                    b.Navigation("Columns");
                });

            modelBuilder.Entity("Domain.Boards.BoardColumn", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("Domain.Organizations.Organization", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("Domain.Projects.Project", b =>
                {
                    b.Navigation("Personas");

                    b.Navigation("Tags");

                    b.Navigation("Teams");

                    b.Navigation("WikiPages");

                    b.Navigation("WorkItems");
                });

            modelBuilder.Entity("Domain.Retrospectives.Retrospective", b =>
                {
                    b.Navigation("Columns");
                });

            modelBuilder.Entity("Domain.Retrospectives.RetrospectiveColumn", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Domain.Sprints.Sprint", b =>
                {
                    b.Navigation("WorkItems");
                });

            modelBuilder.Entity("Domain.Teams.Team", b =>
                {
                    b.Navigation("Board")
                        .IsRequired();

                    b.Navigation("Retrospectives");

                    b.Navigation("Sprints");

                    b.Navigation("WorkItems");
                });

            modelBuilder.Entity("Domain.Users.User", b =>
                {
                    b.Navigation("WorkItems");
                });

            modelBuilder.Entity("Domain.WikiPages.WikiPage", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("SubWikiPages");

                    b.Navigation("Views");
                });

            modelBuilder.Entity("Domain.WorkItems.WorkItem", b =>
                {
                    b.Navigation("ChildWorkItems");

                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
